#!/bin/sh

export GEM_HOME=$HOME/.gem/ruby/1.8
export GEM_PATH=$GEM_HOME
export PATH=$PATH:/usr/local/rvm/rubies/ruby-1.8.7-p334/bin:$HOME/.gem/ruby/1.8/bin

gem install i18n -v 0.4.2 --no-ri --no-rdoc
gem install rake -v 0.8.7 --no-ri --no-rdoc
gem install rails -v 2.3.11 --no-ri --no-rdoc

gem install fcgi --no-ri --no-rdoc
gem install mysql --no-ri --no-rdoc

rake generate_session_store
